version: '3'
services:
  dongurami-server-v2:
    image: hobijeong/dongurami-server-v2
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
    environment:
      - TZ=Asia/Seoul
