/**
 * 0 ~ 999
 */
export const COMMON_ERROR_CODE = {
  SERVER_ERROR: 0,
  INVALID_REQUEST_PARAMETER: 1,
  API_NOT_FOUND: 2,
  INVALID_TOKEN: 3,
  PERMISSION_DENIED: 4,
  RESOURCE_NOT_FOUND: 5,
  MISSING_UPDATE_FIELD: 6,
} as const;
