name: dongurami-server-v2

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and package
        run: |
          npm install
          npm run build
          echo "NODE_ENV=${{ secrets.DEV_NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.DEV_PORT }}" >> .env
          echo "RDB_HOST=${{ secrets.DEV_RDB_HOST }}" >> .env
          echo "RDB_PORT=${{ secrets.DEV_RDB_PORT }}" >> .env
          echo "RDB_USER_NAME=${{ secrets.DEV_RDB_USER_NAME }}" >> .env
          echo "RDB_PASSWORD=${{ secrets.DEV_RDB_PASSWORD }}" >> .env
          echo "RDB_DATABASE=${{ secrets.DEV_RDB_DATABASE }}" >> .env
          cat .env
          sudo docker build --platform linux/amd64 -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest .
        env:
          NODE_ENV: ${{ secrets.DEV_NODE_ENV }}
          PORT: ${{ secrets.DEV_PORT }}
          RDB_HOST: ${{ secrets.DEV_RDB_HOST }}
          RDB_PORT: ${{ secrets.DEV_RDB_PORT }}
          RDB_USER_NAME: ${{ secrets.DEV_RDB_USER_NAME }}
          RDB_PASSWORD: ${{ secrets.DEV_RDB_PASSWORD }}
          RDB_DATABASE: ${{ secrets.DEV_RDB_DATABASE }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: self-hosted # runner로 ec2 연결

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker run
        run: |
          sudo docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:latest
          sudo docker-compose down
          sudo docker-compose up --force-recreate --build -d
