name: Build and Deploy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
		if: ${{ github.ref == 'refs/heads/develop' }}
    ...
# Slack 알림 관련 Job
  slack-notification:
    if: ${{ always() }}
    needs: [deploy-dev, deploy-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Set CUSTOM_STATUS Env Variable
        run: |
          if [ "${{ needs.deploy.result }}" = "failure" ];
          then
            CUSTOM_STATUS="❌ 실패"
          elif [ "${{ needs.deploy.result }}" = "cancelled" ];
          then
            CUSTOM_STATUS="⚠️ 취소"
          else
            CUSTOM_STATUS="✅ 성공"
          fi
          
          echo "CUSTOM_STATUS=${CUSTOM_STATUS}" >> $GITHUB_ENV

      - name: slack-send
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "custom_status": "${{ env.CUSTOM_STATUS }}",
              "workflow": "${{ github.workflow }}",
              "job_deploy_dev": "deploy_dev",
              "status_deploy_dev": "${{ needs.deploy-dev.result }}",
              "actor": "${{ github.actor }}",
              "ref_name": "${{ github.ref_name }}",
              "head_commit_url": "${{ github.event.head_commit.url }}",
              "action_run_url": "${{ env.ACTION_RUN_URL }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"